set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

autocmd FileType python setlocal completeopt-=preview
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugins
Bundle 'The-NERD-tree'
Bundle 'jistr/vim-nerdtree-tabs'
"Bundle 'Rykka/riv.vim'
Bundle 'tomtom/tcomment_vim'
Bundle 'pi314/BoshiamyIM'
Bundle 'pi314/AsciiArt'
Bundle 'tpope/vim-surround'
Bundle 'pi314/pi314.rst.vim'
Bundle 'pi314/todo-or-not-todo.vim'
Bundle 'dhruvasagar/vim-table-mode'
Bundle 'suan/vim-instant-markdown'
Bundle 'davidhalter/jedi-vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
" filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


" Tab char related setting
set nu
highlight LineNr ctermfg=grey

set tabstop=2       " changes the width of the TAB character
set expandtab       " changes user pressed TAB to spaces
set shiftwidth=2    " >>, <<, == width and automatic indent width
set softtabstop=2
set shiftwidth=2
set listchars=tab:>-
set list

"set autoindent
set smarttab

set hlsearch
highlight Comment ctermfg=cyan
" Show the coordinate of cursor
set ru

set cursorline
" setlocal spell spelllang=en_gb

nnoremap <silent> <F5> :NERDTree<CR>

let g:todo_comment_color = 'Yellow'

" put a blue line on column 80
set cc=80
hi ColorColumn ctermbg=Blue


